packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260902.1'
  - '@types/node@26.4.1'
  - globals@17.12.0
  - miniflare@5.20260831.0-alpha
  - wrangler@4.128.0
