/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CareerCareerIdRouteImport } from './routes/career.$careerId'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as CareerCareerIdIndexRouteImport } from './routes/career.$careerId.index'
import { Route as CareerCareerIdConfirmRouteImport } from './routes/career.$careerId.confirm'
import { Route as CareerCareerIdContractRouteImport } from './routes/career.$careerId.contract'
import { Route as CareerCareerIdCreateRouteImport } from './routes/career.$careerId.create'
import { Route as CareerCareerIdEventRouteImport } from './routes/career.$careerId.event'
import { Route as CareerCareerIdOffersRouteImport } from './routes/career.$careerId.offers'
import { Route as CareerCareerIdPathRouteImport } from './routes/career.$careerId.path'
import { Route as CareerCareerIdStyleRouteImport } from './routes/career.$careerId.style'
import { Route as CareerCareerIdTryoutRouteImport } from './routes/career.$careerId.tryout'
import { Route as CareerCareerIdEventResultRouteImport } from './routes/career.$careerId.event_.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCareerIdRoute = CareerCareerIdRouteImport.update({
  id: '/career/$careerId',
  path: '/career/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCareerIdIndexRoute = CareerCareerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdConfirmRoute = CareerCareerIdConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdContractRoute = CareerCareerIdContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdCreateRoute = CareerCareerIdCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdEventRoute = CareerCareerIdEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdOffersRoute = CareerCareerIdOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdPathRoute = CareerCareerIdPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdStyleRoute = CareerCareerIdStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdTryoutRoute = CareerCareerIdTryoutRouteImport.update({
  id: '/tryout',
  path: '/tryout',
  getParentRoute: () => CareerCareerIdRoute,
} as any)
const CareerCareerIdEventResultRoute =
  CareerCareerIdEventResultRouteImport.update({
    id: '/event_/result',
    path: '/event/result',
    getParentRoute: () => CareerCareerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/career/$careerId': typeof CareerCareerIdRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/career/$careerId/confirm': typeof CareerCareerIdConfirmRoute
  '/career/$careerId/contract': typeof CareerCareerIdContractRoute
  '/career/$careerId/create': typeof CareerCareerIdCreateRoute
  '/career/$careerId/event': typeof CareerCareerIdEventRoute
  '/career/$careerId/offers': typeof CareerCareerIdOffersRoute
  '/career/$careerId/path': typeof CareerCareerIdPathRoute
  '/career/$careerId/style': typeof CareerCareerIdStyleRoute
  '/career/$careerId/tryout': typeof CareerCareerIdTryoutRoute
  '/career/$careerId/': typeof CareerCareerIdIndexRoute
  '/career/$careerId/event/result': typeof CareerCareerIdEventResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/career/$careerId/confirm': typeof CareerCareerIdConfirmRoute
  '/career/$careerId/contract': typeof CareerCareerIdContractRoute
  '/career/$careerId/create': typeof CareerCareerIdCreateRoute
  '/career/$careerId/event': typeof CareerCareerIdEventRoute
  '/career/$careerId/offers': typeof CareerCareerIdOffersRoute
  '/career/$careerId/path': typeof CareerCareerIdPathRoute
  '/career/$careerId/style': typeof CareerCareerIdStyleRoute
  '/career/$careerId/tryout': typeof CareerCareerIdTryoutRoute
  '/career/$careerId': typeof CareerCareerIdIndexRoute
  '/career/$careerId/event/result': typeof CareerCareerIdEventResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/career/$careerId': typeof CareerCareerIdRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/career/$careerId/confirm': typeof CareerCareerIdConfirmRoute
  '/career/$careerId/contract': typeof CareerCareerIdContractRoute
  '/career/$careerId/create': typeof CareerCareerIdCreateRoute
  '/career/$careerId/event': typeof CareerCareerIdEventRoute
  '/career/$careerId/offers': typeof CareerCareerIdOffersRoute
  '/career/$careerId/path': typeof CareerCareerIdPathRoute
  '/career/$careerId/style': typeof CareerCareerIdStyleRoute
  '/career/$careerId/tryout': typeof CareerCareerIdTryoutRoute
  '/career/$careerId/': typeof CareerCareerIdIndexRoute
  '/career/$careerId/event_/result': typeof CareerCareerIdEventResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/career/$careerId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/career/$careerId/confirm'
    | '/career/$careerId/contract'
    | '/career/$careerId/create'
    | '/career/$careerId/event'
    | '/career/$careerId/offers'
    | '/career/$careerId/path'
    | '/career/$careerId/style'
    | '/career/$careerId/tryout'
    | '/career/$careerId/'
    | '/career/$careerId/event/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/legal/privacy'
    | '/legal/terms'
    | '/career/$careerId/confirm'
    | '/career/$careerId/contract'
    | '/career/$careerId/create'
    | '/career/$careerId/event'
    | '/career/$careerId/offers'
    | '/career/$careerId/path'
    | '/career/$careerId/style'
    | '/career/$careerId/tryout'
    | '/career/$careerId'
    | '/career/$careerId/event/result'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/settings'
    | '/career/$careerId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/career/$careerId/confirm'
    | '/career/$careerId/contract'
    | '/career/$careerId/create'
    | '/career/$careerId/event'
    | '/career/$careerId/offers'
    | '/career/$careerId/path'
    | '/career/$careerId/style'
    | '/career/$careerId/tryout'
    | '/career/$careerId/'
    | '/career/$careerId/event_/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  CareerCareerIdRoute: typeof CareerCareerIdRouteWithChildren
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$careerId': {
      id: '/career/$careerId'
      path: '/career/$careerId'
      fullPath: '/career/$careerId'
      preLoaderRoute: typeof CareerCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$careerId/': {
      id: '/career/$careerId/'
      path: '/'
      fullPath: '/career/$careerId/'
      preLoaderRoute: typeof CareerCareerIdIndexRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/confirm': {
      id: '/career/$careerId/confirm'
      path: '/confirm'
      fullPath: '/career/$careerId/confirm'
      preLoaderRoute: typeof CareerCareerIdConfirmRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/contract': {
      id: '/career/$careerId/contract'
      path: '/contract'
      fullPath: '/career/$careerId/contract'
      preLoaderRoute: typeof CareerCareerIdContractRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/create': {
      id: '/career/$careerId/create'
      path: '/create'
      fullPath: '/career/$careerId/create'
      preLoaderRoute: typeof CareerCareerIdCreateRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/event': {
      id: '/career/$careerId/event'
      path: '/event'
      fullPath: '/career/$careerId/event'
      preLoaderRoute: typeof CareerCareerIdEventRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/offers': {
      id: '/career/$careerId/offers'
      path: '/offers'
      fullPath: '/career/$careerId/offers'
      preLoaderRoute: typeof CareerCareerIdOffersRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/path': {
      id: '/career/$careerId/path'
      path: '/path'
      fullPath: '/career/$careerId/path'
      preLoaderRoute: typeof CareerCareerIdPathRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/style': {
      id: '/career/$careerId/style'
      path: '/style'
      fullPath: '/career/$careerId/style'
      preLoaderRoute: typeof CareerCareerIdStyleRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/tryout': {
      id: '/career/$careerId/tryout'
      path: '/tryout'
      fullPath: '/career/$careerId/tryout'
      preLoaderRoute: typeof CareerCareerIdTryoutRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$careerId/event_/result': {
      id: '/career/$careerId/event_/result'
      path: '/event/result'
      fullPath: '/career/$careerId/event/result'
      preLoaderRoute: typeof CareerCareerIdEventResultRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
  }
}

interface CareerCareerIdRouteChildren {
  CareerCareerIdConfirmRoute: typeof CareerCareerIdConfirmRoute
  CareerCareerIdContractRoute: typeof CareerCareerIdContractRoute
  CareerCareerIdCreateRoute: typeof CareerCareerIdCreateRoute
  CareerCareerIdEventRoute: typeof CareerCareerIdEventRoute
  CareerCareerIdOffersRoute: typeof CareerCareerIdOffersRoute
  CareerCareerIdPathRoute: typeof CareerCareerIdPathRoute
  CareerCareerIdStyleRoute: typeof CareerCareerIdStyleRoute
  CareerCareerIdTryoutRoute: typeof CareerCareerIdTryoutRoute
  CareerCareerIdIndexRoute: typeof CareerCareerIdIndexRoute
  CareerCareerIdEventResultRoute: typeof CareerCareerIdEventResultRoute
}

const CareerCareerIdRouteChildren: CareerCareerIdRouteChildren = {
  CareerCareerIdConfirmRoute: CareerCareerIdConfirmRoute,
  CareerCareerIdContractRoute: CareerCareerIdContractRoute,
  CareerCareerIdCreateRoute: CareerCareerIdCreateRoute,
  CareerCareerIdEventRoute: CareerCareerIdEventRoute,
  CareerCareerIdOffersRoute: CareerCareerIdOffersRoute,
  CareerCareerIdPathRoute: CareerCareerIdPathRoute,
  CareerCareerIdStyleRoute: CareerCareerIdStyleRoute,
  CareerCareerIdTryoutRoute: CareerCareerIdTryoutRoute,
  CareerCareerIdIndexRoute: CareerCareerIdIndexRoute,
  CareerCareerIdEventResultRoute: CareerCareerIdEventResultRoute,
}

const CareerCareerIdRouteWithChildren = CareerCareerIdRoute._addFileChildren(
  CareerCareerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  CareerCareerIdRoute: CareerCareerIdRouteWithChildren,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
