import { z } from 'zod';

/** 07 "오류 코드" 표와 같은 순서. */
export const ERROR_CODES = [
  'VALIDATION_FAILED',
  'RECOVERY_CODE_INVALID',
  'TOSS_KEY_INVALID',
  'ORIGIN_NOT_ALLOWED',
  'PROFILE_REQUIRED',
  'CAREER_NOT_OWNED',
  'CAREER_NOT_FOUND',
  'CAREER_REVISION_CONFLICT',
  'COMMAND_ALREADY_RESOLVED',
  'RECOVERY_CONFLICT',
  'MERGE_REQUIRED',
  'CAREER_ARCHIVED',
  'VERSION_MISMATCH',
  'VERIFICATION_FAILED',
  'RATE_LIMITED',
  'SERVICE_UNAVAILABLE',
] as const;

export const ErrorCodeSchema = z.enum(ERROR_CODES);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;

type HttpStatus = 400 | 401 | 403 | 404 | 409 | 422 | 429 | 503;

/** 07 "오류 코드" 표의 HTTP 열. */
export const HTTP_STATUS_BY_CODE: Record<ErrorCode, HttpStatus> = {
  VALIDATION_FAILED: 400,
  RECOVERY_CODE_INVALID: 400,
  TOSS_KEY_INVALID: 401,
  ORIGIN_NOT_ALLOWED: 403,
  PROFILE_REQUIRED: 401,
  CAREER_NOT_OWNED: 403,
  CAREER_NOT_FOUND: 404,
  CAREER_REVISION_CONFLICT: 409,
  COMMAND_ALREADY_RESOLVED: 409,
  RECOVERY_CONFLICT: 409,
  MERGE_REQUIRED: 409,
  CAREER_ARCHIVED: 409,
  VERSION_MISMATCH: 422,
  VERIFICATION_FAILED: 422,
  RATE_LIMITED: 429,
  SERVICE_UNAVAILABLE: 503,
};

/** RATE_LIMITED, SERVICE_UNAVAILABLE만 재시도 가능. */
export const RETRYABLE_BY_CODE: Record<ErrorCode, boolean> = {
  VALIDATION_FAILED: false,
  RECOVERY_CODE_INVALID: false,
  TOSS_KEY_INVALID: false,
  ORIGIN_NOT_ALLOWED: false,
  PROFILE_REQUIRED: false,
  CAREER_NOT_OWNED: false,
  CAREER_NOT_FOUND: false,
  CAREER_REVISION_CONFLICT: false,
  COMMAND_ALREADY_RESOLVED: false,
  RECOVERY_CONFLICT: false,
  MERGE_REQUIRED: false,
  CAREER_ARCHIVED: false,
  VERSION_MISMATCH: false,
  VERIFICATION_FAILED: false,
  RATE_LIMITED: true,
  SERVICE_UNAVAILABLE: true,
};
