// T-10-096 나라 영어 이름(FIFA 표기) — 선수 탭 머리글에만 쓴다. 첫 화면 번들에 싣지 않으려고 nations.ts와 따로 둔다.
export const NATION_EN: Record<string, string> = {
  JP: 'Japan',
  KR: 'Korea Republic',
  IR: 'IR Iran',
  AU: 'Australia',
  SA: 'Saudi Arabia',
  UZ: 'Uzbekistan',
  QA: 'Qatar',
  JO: 'Jordan',
  IQ: 'Iraq',
  AE: 'United Arab Emirates',
  OM: 'Oman',
  BH: 'Bahrain',
  SY: 'Syria',
  CN: 'China PR',
  ID: 'Indonesia',
  TH: 'Thailand',
  VN: 'Vietnam',
  KP: 'Korea DPR',
  PS: 'Palestine',
  TJ: 'Tajikistan',
  KW: 'Kuwait',
  KG: 'Kyrgyz Republic',
  LB: 'Lebanon',
  MY: 'Malaysia',
  IN: 'India',
  PH: 'Philippines',
  TM: 'Turkmenistan',
  HK: 'Hong Kong',
  SG: 'Singapore',
  YE: 'Yemen',
  AF: 'Afghanistan',
  TW: 'Chinese Taipei',
  MV: 'Maldives',
  MM: 'Myanmar',
  BD: 'Bangladesh',
  KH: 'Cambodia',
  NP: 'Nepal',
  TL: 'Timor-Leste',
  LA: 'Laos',
  MN: 'Mongolia',
  GU: 'Guam',
  MO: 'Macau',
  BT: 'Bhutan',
  BN: 'Brunei Darussalam',
  LK: 'Sri Lanka',
  PK: 'Pakistan',
  ES: 'Spain',
  FR: 'France',
  'GB-ENG': 'England',
  PT: 'Portugal',
  NL: 'Netherlands',
  DE: 'Germany',
  BE: 'Belgium',
  IT: 'Italy',
  HR: 'Croatia',
  DK: 'Denmark',
  CH: 'Switzerland',
  NO: 'Norway',
  AT: 'Austria',
  TR: 'Türkiye',
  UA: 'Ukraine',
  RS: 'Serbia',
  SE: 'Sweden',
  'GB-SCT': 'Scotland',
  PL: 'Poland',
  HU: 'Hungary',
  CZ: 'Czechia',
  'GB-WLS': 'Wales',
  RO: 'Romania',
  IE: 'Republic of Ireland',
  GR: 'Greece',
  RU: 'Russia',
  SK: 'Slovakia',
  AL: 'Albania',
  GE: 'Georgia',
  SI: 'Slovenia',
  BA: 'Bosnia and Herzegovina',
  FI: 'Finland',
  MK: 'North Macedonia',
  'GB-NIR': 'Northern Ireland',
  IS: 'Iceland',
  IL: 'Israel',
  ME: 'Montenegro',
  BG: 'Bulgaria',
  XK: 'Kosovo',
  KZ: 'Kazakhstan',
  LU: 'Luxembourg',
  BY: 'Belarus',
  AM: 'Armenia',
  AZ: 'Azerbaijan',
  CY: 'Cyprus',
  EE: 'Estonia',
  LV: 'Latvia',
  FO: 'Faroe Islands',
  LT: 'Lithuania',
  MD: 'Moldova',
  MT: 'Malta',
  AD: 'Andorra',
  GI: 'Gibraltar',
  LI: 'Liechtenstein',
  SM: 'San Marino',
  AR: 'Argentina',
  BR: 'Brazil',
  UY: 'Uruguay',
  CO: 'Colombia',
  EC: 'Ecuador',
  PY: 'Paraguay',
  CL: 'Chile',
  PE: 'Peru',
  VE: 'Venezuela',
  BO: 'Bolivia',
  MA: 'Morocco',
  SN: 'Senegal',
  DZ: 'Algeria',
  EG: 'Egypt',
  NG: 'Nigeria',
  CI: "Côte d'Ivoire",
  GH: 'Ghana',
  ML: 'Mali',
  CM: 'Cameroon',
  TN: 'Tunisia',
  CD: 'Congo DR',
  ZA: 'South Africa',
  BF: 'Burkina Faso',
  CV: 'Cabo Verde',
  GA: 'Gabon',
  GN: 'Guinea',
  BJ: 'Benin',
  AO: 'Angola',
  ZM: 'Zambia',
  UG: 'Uganda',
  GQ: 'Equatorial Guinea',
  MZ: 'Mozambique',
  TZ: 'Tanzania',
  GW: 'Guinea-Bissau',
  NA: 'Namibia',
  MG: 'Madagascar',
  MR: 'Mauritania',
  ZW: 'Zimbabwe',
  KM: 'Comoros',
  GM: 'Gambia',
  LY: 'Libya',
  KE: 'Kenya',
  CG: 'Congo',
  NE: 'Niger',
  SD: 'Sudan',
  TG: 'Togo',
  MW: 'Malawi',
  SL: 'Sierra Leone',
  RW: 'Rwanda',
  LR: 'Liberia',
  BW: 'Botswana',
  BI: 'Burundi',
  ET: 'Ethiopia',
  LS: 'Lesotho',
  CF: 'Central African Republic',
  SS: 'South Sudan',
  MU: 'Mauritius',
  SZ: 'Eswatini',
  DJ: 'Djibouti',
  TD: 'Chad',
  ST: 'São Tomé and Príncipe',
  SC: 'Seychelles',
  SO: 'Somalia',
  ER: 'Eritrea',
  MX: 'Mexico',
  US: 'USA',
  CA: 'Canada',
  PA: 'Panama',
  JM: 'Jamaica',
  CR: 'Costa Rica',
  HT: 'Haiti',
  HN: 'Honduras',
  CW: 'Curaçao',
  GT: 'Guatemala',
  SV: 'El Salvador',
  SR: 'Suriname',
  TT: 'Trinidad and Tobago',
  CU: 'Cuba',
  GY: 'Guyana',
  NI: 'Nicaragua',
  DO: 'Dominican Republic',
  BM: 'Bermuda',
  GD: 'Grenada',
  PR: 'Puerto Rico',
  BB: 'Barbados',
  BZ: 'Belize',
  LC: 'St. Lucia',
  KN: 'St. Kitts and Nevis',
  AW: 'Aruba',
  AG: 'Antigua and Barbuda',
  BS: 'Bahamas',
  KY: 'Cayman Islands',
  DM: 'Dominica',
  MS: 'Montserrat',
  VI: 'US Virgin Islands',
  AI: 'Anguilla',
  NZ: 'New Zealand',
  NC: 'New Caledonia',
  SB: 'Solomon Islands',
  FJ: 'Fiji',
  VU: 'Vanuatu',
  PF: 'Tahiti',
  PG: 'Papua New Guinea',
  WS: 'Samoa',
  AS: 'American Samoa',
  CK: 'Cook Islands',
  TO: 'Tonga',
  VC: 'St. Vincent and the Grenadines',
  VG: 'British Virgin Islands',
  TC: 'Turks and Caicos Islands',
};
